name: Generate Section Index
on:
  push:
    paths:
      - "1_Engineering_Craft/**"
      - "2_Thinking_Tools/**"
      - "3_Personal_Growth/**"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "lts/*" }
      - run: node scripts/gen-index.mjs
      - name: Commit index updates
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "docs(index): auto-update section README"
            git push
          else
            echo "no changes"
          fi
